// <auto-generated>
// This file was generated by tools/generate_schema.py.
// Do not edit manually. Edit tools/schema_def.py instead,
// then re-run: python tools/generate_schema.py
// </auto-generated>

namespace LLiquidLink
{

    /// <summary>
    /// Represents a .NET Type reference transmitted as a JSON-RPC parameter.
    /// </summary>
    public partial class RpcType
    {
        public long? rpcType { get; set; }
        public string value { get; set; }
    }

    /// <summary>
    /// Single step in a property/method chain resolved server-side.
    /// </summary>
    public partial class RpcChainStep
    {
        public string name { get; set; }
    }

    /// <summary>
    /// JSON-serializable descriptor for a live Unity Object instance.
    /// </summary>
    public partial class RpcUnityObject
    {
        public long instanceId { get; set; }
        public long? instanceObjectAttr { get; set; }
        public string name { get; set; }
        public string orgType { get; set; }
        public string rpcType { get; set; }
    }

    /// <summary>
    /// Represents a .NET Type reference transmitted as a JSON-RPC parameter.
    /// </summary>
    public partial class RpcEnum
    {
        public long? rpcEnum { get; set; }
        public string value { get; set; }
    }
}
