"""RPC wire-protocol type definitions.

Auto-generated by tools/generate_schema.py.
Do not edit manually. Edit tools/schema_def.py and re-run the generator.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal


@dataclass
class RpcType:
    """Represents a .NET Type reference transmitted as a JSON-RPC parameter."""

    value: str
    rpcType: int = 1


@dataclass
class RpcChainStep:
    """Single step in a property/method chain resolved server-side."""

    name: str


@dataclass
class RpcEnum:
    """Represents a .NET enum reference transmitted as a JSON-RPC parameter."""

    value: str
    rpcEnum: int = 1


@dataclass
class RpcResolveChainParam:
    obj: Any
    steps: list[RpcChainStep]
    method: str
    args: list[Any]


@dataclass
class RpcResolveChainSetParam:
    obj: Any
    steps: list[RpcChainStep]
    property: str
    value: Any
