// <auto-generated>
// This file was generated by tools/generate_fallback_converters.py.
// Do not edit manually. Edit tools/fallback_converters.csv instead,
// then re-run: python tools/generate_fallback_converters.py
// </auto-generated>
namespace UniLiquidLink
{
    public partial class Server
    {
        protected override void AddFallbackConverters()
        {
            Rpc.AddFallbackConverterFactory(new JsonUtilityConverterFactory());
        }
    }
}
