// <auto-generated>
// This file was generated by tools/generate_converters.py.
// Do not edit manually. Edit tools/converters.csv instead,
// </auto-generated>
using LLiquidLink;
namespace UniLiquidLink
{
    public partial class Server
    {
        protected override void AddConverters()
        {
            Rpc.AddRpcConverter(new TypeConverter(_typeResolver));
            Rpc.AddRpcConverter(new EnumConverter());
            Rpc.AddRpcConverter(new UnityObjectConverter(_registry));
            Rpc.AddPreConverter(new PreObjectConverter(_registry));
            Rpc.AddRpcConverter(new ObjectPrimitiveConverter());
        }
    }
}
